import "./globals.css";
import { cookies } from "next/headers";

import { TRPCReactProvider } from "@/trpc/react";
import { SessionProvider } from "@/providers/session";
import { ThemeProvider } from "@/providers/theme";
import { Toaster } from "@/components/ui/sonner";

export const metadata = {
  title: "Chess",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <TRPCReactProvider cookies={cookies().toString()}>
            {children}
            <Toaster />
          </TRPCReactProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
